// Code generated by "stringer -type=Tok -linecomment"; DO NOT EDIT.

package lexer

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EOF-0]
	_ = x[Illegal-1]
	_ = x[Comment-2]
	_ = x[Identifier-3]
	_ = x[LeftParen-4]
	_ = x[RightParen-5]
	_ = x[LeftBracket-6]
	_ = x[RightBracket-7]
	_ = x[LeftBrace-8]
	_ = x[RightBrace-9]
	_ = x[Comma-10]
	_ = x[Semicolon-11]
	_ = x[Plus-12]
	_ = x[Minus-13]
	_ = x[Multiply-14]
	_ = x[Divide-15]
	_ = x[And-16]
	_ = x[Or-17]
	_ = x[Implies-18]
	_ = x[Less-19]
	_ = x[LessEq-20]
	_ = x[Equal-21]
	_ = x[NotEqual-22]
	_ = x[Greater-23]
	_ = x[GreaterEq-24]
	_ = x[In-25]
	_ = x[Is-26]
	_ = x[Not-27]
	_ = x[I64Lit-28]
	_ = x[F64Lit-29]
	_ = x[StringLit-30]
	_ = x[True-31]
	_ = x[False-32]
	_ = x[Bool-33]
	_ = x[I64-34]
	_ = x[F64-35]
	_ = x[String-36]
	_ = x[Assert-37]
	_ = x[Break-38]
	_ = x[Continue-39]
	_ = x[Else-40]
	_ = x[For-41]
	_ = x[If-42]
}

const _Tok_name = "EOFillegalcommentidentifier()[]{},;+-·÷∧∨⟹<≤=≠>≥∈is¬i64 literalf64 literalstring literaltruefalsebooli64f64stringassertbreakcontinueelseforif"

var _Tok_index = [...]uint8{0, 3, 10, 17, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 39, 41, 44, 47, 50, 51, 54, 55, 58, 59, 62, 65, 67, 69, 80, 91, 105, 109, 114, 118, 121, 124, 130, 136, 141, 149, 153, 156, 158}

func (i Tok) String() string {
	if i < 0 || i >= Tok(len(_Tok_index)-1) {
		return "Tok(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Tok_name[_Tok_index[i]:_Tok_index[i+1]]
}
