// Code generated by "stringer -type=RegType -linecomment"; DO NOT EDIT.

package ir

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BoolReg-0]
	_ = x[F64Reg-1]
	_ = x[I64Reg-2]
}

const _RegType_name = "boolf64i64"

var _RegType_index = [...]uint8{0, 4, 7, 10}

func (i RegType) String() string {
	if i < 0 || i >= RegType(len(_RegType_index)-1) {
		return "RegType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RegType_name[_RegType_index[i]:_RegType_index[i+1]]
}
