// Code generated by "stringer -type=Op -linecomment"; DO NOT EDIT.

package compiler

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Movq-0]
	_ = x[Movb-1]
	_ = x[Push-2]
	_ = x[Pop-3]
	_ = x[Jump-4]
	_ = x[CJump-5]
	_ = x[Neg-6]
	_ = x[Add-7]
	_ = x[Sub-8]
	_ = x[Mul-9]
	_ = x[Div-10]
	_ = x[And-11]
	_ = x[Or-12]
	_ = x[Cmpq-13]
	_ = x[Cmpb-14]
	_ = x[Setl-15]
	_ = x[Setle-16]
	_ = x[Sete-17]
	_ = x[Setne-18]
	_ = x[Setg-19]
	_ = x[Setge-20]
	_ = x[Call-21]
}

const _Op_name = "movqmovbpushqpopqjmpjenegqaddqsubqimulqidivandborbcmpqcmpbsetlsetlesetesetnesetgsetgecall"

var _Op_index = [...]uint8{0, 4, 8, 13, 17, 20, 22, 26, 30, 34, 39, 43, 47, 50, 54, 58, 62, 67, 71, 76, 80, 85, 89}

func (i Op) String() string {
	if i < 0 || i >= Op(len(_Op_index)-1) {
		return "Op(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Op_name[_Op_index[i]:_Op_index[i+1]]
}
